import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Netflix Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-xl text-blue-700'>Hello World!</h1>
    </div>
  );
}
